DROP DATABASE IF EXISTS Employee_tracker;

CREATE DATABASE Employee_tracker;

USE Employee_tracker;
-- Makes the tables for databases. --
-- DEPARTMENT DATABASE SIDENOTE: I'M STARTITING TO LEARN HOW DATABASES ARE MADE AT MY STORE. --
CREATE TABLE departments (
id INT NOT NULL AUTO_INCREMENT, 
dept_name VARCHAR(30) NOT NULL,
PRIMARY KEY (id));

-- ROLE TABLE --

CREATE TABLE roles (
id INT NOT NULL AUTO_INCREMENT,
title TEXT NOT NULL,
salary INTEGER,
department_id INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE
);


-- EMPLOYEE TABLE --

CREATE TABLE employees (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL, 
role_id INT NOT NULL, 
department_id INT NOT NULL,
FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
FOREIGN KEY (department_id) REFERENCES departments(id)
);
